Navbar: fix exception on custom IME button
Custom IME buttons were created as KeyButtonView instead of
LayoutChangerButtonView. Fix this by checking at least the
singleAction if it is an IME action and if so, create the
button from the right class.

java.lang.ClassCastException: com.android.systemui.statusbar.policy.KeyButtonView
   cannot be cast to com.android.systemui.statusbar.policy.LayoutChangerButtonView
at com.android.systemui.statusbar.phone.NavigationBarView.setLayoutChangerType(NavigationBarView.java:587)
at com.android.systemui.statusbar.phone.NavigationBarView.setNavigationIconHints(NavigationBarView.java:554)
at com.android.systemui.statusbar.phone.PhoneStatusBar.forceNavigationIconHints(PhoneStatusBar.java:3663)

Change-Id: I89596fa4c3cc82ff8c9239894a59776ac05434e3