Fix NPE in navbar with ACTION_IME being null
Added null check due to exception like this:
java.lang.NullPointerException: Attempt to invoke virtual method
    'void android.view.View.setVisibility(int)' on a null object reference
  at com.android.systemui.statusbar.phone.NavigationBarView
     .setNavigationIconHints(NavigationBarView.java:503)
  at com.android.systemui.statusbar.phone.NavigationBarView

Change-Id: I754cc5564cddf51c1aecfb6232d6a1d0de17d603